# Generated by Django 3.0.4 on 2020-03-29 19:26

from django.db import migrations, models
import hypertest.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_vkusertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkusertoken',
            name='token',
            field=models.CharField(blank=True, default=hypertest.user.models.generate_unique_vk_user_token, max_length=24, null=True, unique=True, verbose_name='Token'),
        ),
    ]
