# Generated by Django 3.0.4 on 2020-03-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestionanswer',
            options={'verbose_name': 'Test question answer', 'verbose_name_plural': 'Test question answers'},
        ),
        migrations.AlterModelTable(
            name='testquestionanswer',
            table='test_question_answer',
        ),
    ]
