# Generated by Django 3.0.4 on 2020-03-29 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vkuser'),
        ('main', '0002_result_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='user.VKUser', verbose_name='Creator'),
        ),
    ]
