# Generated by Django 3.0.4 on 2020-04-01 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200329_2326'),
        ('main', '0003_test_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='main.Test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_passed', to='user.VKUser', verbose_name='VK User')),
            ],
            options={
                'verbose_name': 'Test pass',
                'verbose_name_plural': "Tests' passes",
                'db_table': 'test_pass',
            },
        ),
    ]
