# Generated by Django 3.0.4 on 2020-04-02 16:56

from django.db import migrations, models


def set_passed(apps, schema_editor):
    Test = apps.get_model('main', 'Test')
    TestPass = apps.get_model('main', 'TestPass')
    for test in Test.objects.all():
        test.passed_count = TestPass.objects.filter(test=test).count()
        test.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_testpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='passed_count',
            field=models.IntegerField(default=0, verbose_name='Passed count'),
        ),

        migrations.RunPython(set_passed),
    ]
