# Generated by Django 3.0.4 on 2020-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testpass_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testpass',
            constraint=models.UniqueConstraint(fields=('test', 'user'), name='test_pass_unique_idx'),
        ),
    ]
